### ISSUE TITLE
LNS: Wallets should remember the original name for the LNS record in their cache

### ISSUE THREAD

**Issue by Doy-lee** [loki-project/loki-core#1077]
When names enter the LNS DB, they are hashed and stored- meaning when you query a record by searching up the owner of the records you receive the hashed version of the name rather than the original.

The originating wallet that made the transaction can store the original name of the LNS record when they make the purchasing transaction into the wallet cache, similar to how notes are stored in wallets.

This information though is lost if the wallet is regenerated from seed. 

This is currently an example of what it looks like for a wallet to query it's owner. Note the `name_hash` returned.

```
[wallet TRrVM1]: lns_print_owners_to_names
owner=TRrVM1Xq7uvgwQGZLg1EijZniiKaANugaZsNQKRv1NXnRZ95MVudVqeUszmyRbEZD9AonvP4SFJoBRwX3niiDAoL2MdQht4p9, backup_owner=(none), type=session, height=205, name_hash=Mk3PAn3UowqTLEQfNlol6GsXPe+kuOWJSCU0cbgbcs8=, encrypted_value=da66f1d81e05e4d265cea6821f53698365a284f97fb6d65fcaf839351c1cf82e337c4c6afb6169905577e167519e69709c, prev_txid=72e61a0963079cb5609ddf7
481185c11147f0806b61cdfe3e2cda834cbf8bdd0
```

Given the `name` the wallet is also able to decode the encrypted value into the real value as well. (Names are hashed, and the value is encrypted using the pre-hashed name.)

**Comment by darcys22** [comment]
Would this just involve adding another map onto the `wallet2` class?

Say
```
std::unordered_map<crypto::hash, std::string> m_lns_names;
``

and writing to it after a buy/update? Would the wallet serialisation handle saving that automatically?

**Comment by Doy-lee** [comment]
That would be appropriate. You will also need to add the serialisation code in wallet2.h, if you search for `m_tx_notes` you can see how it's serialized, it looks like it's just a one liner to get it saved.

Potentially you would also want to save more than just the name. You could imagine that if you have the wallet offline, typically you'd still expect to be able query your LNS records.

**Comment by darcys22** [comment]
So I'm having some trouble with the serialisation part of the cache:

Ive created a new struct in `wallet2.h` as follows:

```    
struct lns_detail
    {
      lns::mapping_type type;
      std::string name;
      std::string value;
      std::string owner;
      std::string backup_owner;

      BEGIN_SERIALIZE_OBJECT()
        FIELD(type);
        FIELD(name);
        FIELD(value);
        FIELD(owner);
        FIELD(backup_owner);
      END_SERIALIZE()

    };

std::vector<lns_detail> lns_records_cache;
```
Then down the bottom of the file I've also added in the lns_records_cache to one of the SERIALIZE methods:

```
    template <class t_archive>
    inline void serialize(t_archive &a, const unsigned int ver)
    {
      uint64_t dummy_refresh_height = 0; // moved to keys file
...
      a & m_transfers;
      a & m_account_public_address;
      a & m_key_images;
      a & lns_records_cache;
...

But getting some errors and partially because I don't understand the serialize macro very well.

```
struct tools::wallet2::lns_detail’ has no member named ‘serialize’; did you mean ‘do_serialize’?
         t.serialize(ar, file_version);
```

Could I request some assistance?
```

**Comment by Doy-lee** [comment]
Ah yeah, for this. 

You need a custom serialize function for `lns_detail` like they do it at the bottom of wallet2.h for other custom types.

``` cpp
    inline void serialize(Archive &a, tools::wallet2::transfer_details &x, const boost::serialization::version_type ver)
```

I'm not sure you need the `BEGIN_SERIALIZE_OBJECT()` actually in that case if you are just serializing out primitive fields in the new serialize function but you'll have to double check.
