### ISSUE TITLE
Generating view key without a password has an error when importing key images

### ISSUE THREAD

**Issue by tokerato** [loki-project/loki-core#1120]
Exporting key image on Ubuntu 16.04 wallet version v6.xxxx and v7.1.xx - importing key image to linux distribution/wallet of same version is working successfully.

Importing key image on Windows operating system/wallet of same version is not working.

![pastedImage](https://user-images.githubusercontent.com/26150486/78956332-280d3680-7b0c-11ea-860d-4273de3d542c.png)

**Comment by Doy-lee** [comment]
Can you verify the file imported on Windows has not been corrupted in some form? You can do this by hashing the original and comparing it with the file hash on Windows.

A failure 1,551 key images in the signature is very unusual as the signatures (which verify the key images) are signed by your wallet keys, and doesn't change throughout the 7,517 key images being imported, which appears to suggest file corruption.

**Comment by tokerato** [comment]
Retitled bug; the issue is not due to operating system or corrupted key image file.

Issue was replicated on Linux host by generating a view key without a password and re-attempting key image import.
