### ISSUE TITLE
Staking - calculation of minimum staking requirement

### ISSUE THREAD

**Issue by Shraier** [loki-project/loki-core#1137]
**Describe the bug**
The bug persists when a service node is registered on the network with a reserved spot for one contributor and the remaining portion is open for anyone. While the spot for the second contributor (reserved one) is still untouched (not staked), the network (service node) accepts a contribution from any contributor (filling the remaining portion) whereby the calculation for the minimum contribution requirement divides the _**remaining portion/3 spots**_ while it should divide it by _**2 spots**_ since 1 spot is reserved for the second contributor.

**To  Reproduce**
- Register a service node with one additional contributor and leave an open portion (let's say the staking requirement is 18000, the operator contributes 5000 lokis, the reservation for one additional contributor is 5000 and 8000 is open to anyone)
- DO NOT stake the reserved contribution for contributor1
- Now the remaining portion to be contributed is 18000 - 5000 (op) - 5000 (contrib1, not staked but reserved) = 8000 open to anyone (for 2 spots)
- The minimum staking requirement should be 8000/2 spots = 4000 lokis, but the network (sn) accepts a contribution with 8000/3 spots = ~2666.66 lokis

**Expected behaviour**
I believe the math for the minimum staking requirement should take in consideration also the reserved spot.

**Current Behaviour**
The calculation for the minimum staking requirement does not take in consideration the reserved spot but _**total amount-staked amount**_.

**Additional Information:**
 - Loki daemon version 7.1.x

**Comment by jagerman** [comment]
Fixed (for loki 8) by #1215.  The wallet will start doing this properly as soon as it gets upgraded, and it will start being enforced by the network at the hard fork height.
