### ISSUE TITLE
Implementation Of Loki Service Node

### ISSUE THREAD

**Issue by coinevo** [loki-project/loki-core#1144]
I seek to implement the loki service node system into [https://github.com/coinevo/coinevo-core.git](https://github.com/coinevo/coinevo-core.git) , in this method those running coinevo node will receive payments for doing so but will have to hold a certain amount of coinevo to run this node and also will receive payment for it. I will need help towards achieving it. Thanks

**Comment by Doy-lee** [comment]
The entry point into service node code is here: https://github.com/loki-project/loki-core/blob/8f6ecf4c2cf3fe29ec9de85b8fd7ea356b07539d/src/cryptonote_core/service_node_list.cpp#L1128

There's a description of how staking amounts are verified is done via: https://github.com/loki-project/loki-core/blob/8f6ecf4c2cf3fe29ec9de85b8fd7ea356b07539d/src/cryptonote_core/service_node_list.cpp#L643

You then go and derive Service Node state from data stored on the blockchain as they are added. That's basically it. This isn't really a issue relating to Loki so I will close this.

A high level overview of Service Nodes is at docs.loki.network and the code has everything else for everything low level.
