### ISSUE TITLE
Lokid  last 30 minutes, there might be large hash rate changes

### ISSUE THREAD

**Issue by Stardock2018** [loki-project/loki-core#1164]
**Describe the bug**
2020-05-29 18:27:26.517 W There were 2 blocks in the last 30 minutes, there might be large hash rate changes, or we might be partitioned, cut off from the Loki network or under attack. Or it could be just sheer bad luck.

**To Reproduce**
The message popups every 5 or 6 hours

**Expected behaviour**
What is the expected behaviour if the steps above are followed:

**Current Behaviour**
What is the current behaviour if the steps to reproduce are followed:

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

**Additional Information (please complete the following information):**
 - Operating System: [e.g. Ubuntu 18.04, ]
-  Local node
 -
Loki 'Valiant Vidar' (v7.1.9-397229f83)

**Comment by jagerman** [comment]
It's usually safe to ignore that error if it just pops up occassionally -- the check (added by upstream monero) is overly sensitive and results in false positives a couple times a day just caused by random hashing luck and (small) network hashrate fluctuations.

**Comment by Stardock2018** [comment]
TY
