### ISSUE TITLE
Blink Bug V.7.1.9 In LOKI CORE

### ISSUE THREAD

**Issue by SomethingGettingWrong** [loki-project/loki-core#1165]
**blink transfer not defaulting in latest v7.1.9**

When typing **Transfer Address Amount** to send a blink transaction in the Cli wallet even though its set priority 0  it does not send blink and the fee remains 0.04. The expected behavior is to default to BLINK without specification.

![image](https://user-images.githubusercontent.com/36722911/83342713-33811080-a2b8-11ea-84ca-f1ac270f5b47.png)

When typing  **Transfer Blink Address Amount** to send a blink transaction it goes through properly and has the blink fee of 0.1 

When sending with the default **Transfer Address Amount** to Tradeogre I takes about 10 blocks before tradeable. By manually specifiying **Transfer Blink Address Amount** the loki was avaiable within 15 seconds and tradeable. 

![image](https://user-images.githubusercontent.com/36722911/83342862-b8b8f500-a2b9-11ea-93e3-dbf6e7847fad.png)

Unsure what revision of the wallet the bug started.

**Comment by jagerman** [comment]
Fixed in #1166
