### ISSUE TITLE
Ubuntu 20.04  cmake update required for compilation

### ISSUE THREAD

**Issue by SomethingGettingWrong** [loki-project/loki-core#1167]
installed all perquisite dependencies. 
sudo apt update && sudo apt install build-essential cmake pkg-config libboost-all-dev libssl-dev libzmq3-dev libunbound-dev libsodium-dev libunwind8-dev liblzma-dev libreadline6-dev libldns-dev libexpat1-dev doxygen graphviz libpgm-dev libsqlite3-dev

 Getting Cmake error  saying boost is to old to work with this verison of openSSL even though both are compatible for some reason it thinks 1.71.0 is older then 1.6.2

-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.1.1f")
-- Found Boost Version: 1.71.0

CMake Error at CMakeLists.txt:791 (message):
  Boost older than 1.62 is too old to link with OpenSSL 1.1 or newer.  Update
  Boost or install OpenSSL 1.0 and set path to it when running cmake: cmake
  -DOPENSSL_ROOT_DIR='/usr/include/openssl-1.0;/usr/lib/openssl-1.0'

**Comment by jagerman** [comment]
Have you modified anything, and what branch are you on?  That message isn't on (or even all that close to) that particular line of CMakeLists.txt in any of dev, master, or v7.1.9.

**Comment by SomethingGettingWrong** [comment]
Im going to close this. I just uninstalled reinstalled boost and rm -rf loki  and  recloned and is now working.
