### ISSUE TITLE
FreeBSD build fails. Related to lokimq

### ISSUE THREAD

**Issue by dfiguera** [loki-project/loki-core#1187]
The relevant output fragment goes below.

I installed the dependencies following the indications in the README.md

The first iteration, I wondered if maybe the cause was that some package was at a lower version of what loki expected, so I changed the repo to get "latest" instead of "quarterly" packages with no luck.

**Screenshots or Logs**
Scanning dependencies of target lokimq
gmake[3]: Leaving directory '/usr/home/build/loki/build/FreeBSD/master/release'
gmake[3]: Entering directory '/usr/home/build/loki/build/FreeBSD/master/release'
[ 20%] Building CXX object external/loki-mq/CMakeFiles/lokimq.dir/lokimq/auth.cpp.o
[ 21%] Building CXX object external/loki-mq/CMakeFiles/lokimq.dir/lokimq/bt_serialize.cpp.o
[ 21%] Building CXX object external/loki-mq/CMakeFiles/lokimq.dir/lokimq/connections.cpp.o
[ 21%] Building CXX object external/loki-mq/CMakeFiles/lokimq.dir/lokimq/jobs.cpp.o
[ 21%] Building CXX object external/loki-mq/CMakeFiles/lokimq.dir/lokimq/lokimq.cpp.o
[ 21%] Building CXX object external/loki-mq/CMakeFiles/lokimq.dir/lokimq/proxy.cpp.o
/home/build/loki/external/loki-mq/lokimq/proxy.cpp:299:5: error: use of undeclared identifier
      'pthread_set_name_np'
    pthread_set_name_np(pthread_self(), "lmq-proxy");
    ^
1 error generated.

**Additional Information**
- Operating System: FreeBSD/amd64 12.1-RELEASE-p6
- Version of Loki: 7.1.9

**Comment by jagerman** [comment]
It looks like the thread naming code I borrowed from lokinet doesn't work right (or perhaps I made a mistake in copying it).  Looking at it now.

**Comment by dfiguera** [comment]
I've tried your patch. Unfortunately there's more errors.

Scanning dependencies of target lmdb
gmake[3]: Leaving directory '/usr/home/build/loki/build/FreeBSD/master/release'
gmake[3]: Entering directory '/usr/home/build/loki/build/FreeBSD/master/release'
[ 23%] Building C object external/db_drivers/liblmdb/CMakeFiles/lmdb.dir/mdb.c.o
/usr/home/build/loki/external/db_drivers/liblmdb/mdb.c:5171:14: error: variable has incomplete type 'union semun'
union semun semu;
^
/usr/home/build/loki/external/db_drivers/liblmdb/mdb.c:5171:8: note: forward declaration of 'union semun'
union semun semu;
^
1 error generated.

**Comment by jagerman** [comment]
That error looks like it is fixed on the `dev` branch (via the recent Monero merge https://github.com/loki-project/loki-core/commit/757b789c3047d2659af15d1f3d6e484f7893f8b9), but I'll backport it to master as well along with the fixed loki-mq submodule commit.  Give #1188 a try; I set up a FreeBSD 12.4 VM that successfully built from that branch.
