### ISSUE TITLE
Feature request to support for NGRAVE cold wallet

### ISSUE THREAD

**Issue by anon1972** [loki-project/loki-core#1247]
This is not a bug but a feature request for Loki to be supported for the NGRAVE cold wallet. Further information can be found here:

https://www.ngrave.io/

At the moment, the coins that are supported can be found here:

https://www.ngrave.io/products/zero

Note: All supported coins can be found near bottom of the page.

**Suggestion/Observation**

Loki Cryptocurrency would be a perfect compliment to this new hardware wallet as a symbiotic pair in support of strong security and privacy.

**Comment by KeeJef** [comment]
Integration into any hardware wallet is difficult if they don't already support Monero, we are working hard on Ledger integration right now

**Comment by anon1972** [comment]
Understood. I have also chatted with COO Edouard Vanham and he indicated the same. They have added XMR to Coin list after they launch.
