### ISSUE TITLE
wallet-rpc transfer return error but transaction success

### ISSUE THREAD

**Issue by ccdonn** [loki-project/loki-core#1251]
**Describe the bug**
i run a testnet fullnode, 
call wallet-rpc with "method":"get_transfers", trying to send some LOKI coin from one wallet to another wallet.
eventhough the transfer return an error, the transaction still be successful.

**To Reproduce**
1. call wallet-rpc with "method": "transfer", to send amount from one wallet to another wallet.

**Expected behaviour**
What is the expected behaviour if the steps above are followed:

if transfer return error, the transaction should be fail.
if transfer return success, rpc should return txid and so on.

**Current Behaviour**
What is the current behaviour if the steps to reproduce are followed:

return error but transaction success.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

transfer request
```
"method": "transfer",
  "params": {
    "destinations": [{
      "address": "T6S8pDTQdykGoLfnRg7HGuazqmYsLS9reD3BZ94XshVAfWukh9b24BhbxnqvoJyV1Q4EJVG6pbFGk9xY2xJ9d7Gk26Mayoh2v",
      "amount": 10000
    }],
    "account_index": 0,
    "subaddr_indices": [0],
    "get_tx_hex": true,
    "get_tx_metadata": true
  }
```

transfer response
```
{
  "error": {
    "code": -1000,
    "message": "Transaction was not accepted blink quorum: Blink quorum timeout"
  },
  "id": "0",
  "jsonrpc": "2.0"
}
```

on wallet-rpc side log for both

`FROM` wallet
```
2020-09-14 10:56:42.317	E daemon_send_resp.status != CORE_RPC_STATUS_OK. THROW EXCEPTION: error::tx_blink_rejected
2020-09-14 10:56:43.335	W Received money: 999.496406660, with tx: <f36517f2ede4d2e03dc245fe08bc92bbc241021819bf4e60cdc5c03313cab04e>
2020-09-14 11:07:03.718	W Spent money: 999.597127140, with tx: <f36517f2ede4d2e03dc245fe08bc92bbc241021819bf4e60cdc5c03313cab04e>
```

`TO` wallet
```
2020-09-14 10:56:54.724	W Received money: 0.000010000, with tx: <f36517f2ede4d2e03dc245fe08bc92bbc241021819bf4e60cdc5c03313cab04e>
2020-09-14 10:57:14.746	E blink && transfer.m_unmined_blink. THROW EXCEPTION: error::wallet_internal_error
2020-09-14 10:57:34.763	E blink && transfer.m_unmined_blink. THROW EXCEPTION: error::wallet_internal_error
2020-09-14 10:57:54.784	E blink && transfer.m_unmined_blink. THROW EXCEPTION: error::wallet_internal_error
2020-09-14 10:58:14.802	E blink && transfer.m_unmined_blink. THROW EXCEPTION: error::wallet_internal_error
2020-09-14 10:58:34.824	E blink && transfer.m_unmined_blink. THROW EXCEPTION: error::wallet_internal_error
2020-09-14 10:58:54.842	E blink && transfer.m_unmined_blink. THROW EXCEPTION: error::wallet_internal_error
```

**Additional Information (please complete the following information):**
 - Operating System: Centos 7 
-  Local or Remote node: i run a testnet fullnode myself, and use the wallet-rpc on the same server
 - Version of Loki daemon, or most recent commit hash: Valiant Vidar 7.1.9

**Comment by Doy-lee** [comment]
If you're testing on testnet, we're currently using the dev branch which has a couple of Blink fixes and also one regarding timeout, namely https://github.com/loki-project/loki-core/pull/1237 which hasn't been merged yet to dev, only our pulse branch.

I'll setup a merge for that shortly

**Comment by Doy-lee** [comment]
Actually this is already merged in https://github.com/loki-project/loki-core/commit/fdead9663717c00bf75b7979c3fe7b21d8279491, can you try on the dev branch?

**Comment by ccdonn** [comment]
ohoh, ok. let me try dev branch.

thanks for response.

**Comment by ccdonn** [comment]
unfortunately, i cannot build lokid and so on with branch dev on ubuntu16.04.6

i got following message
```
[ 17%] Building CXX object external/loki-mq/CMakeFiles/lokimq.dir/lokimq/jobs.cpp.o
/home/ubuntu/loki/external/loki-mq/lokimq/jobs.cpp: In member function 'lokimq::TaggedThreadID lokimq::LokiMQ::add_tagged_thread(std::__cxx11::string, std::function<void()>)':
/home/ubuntu/loki/external/loki-mq/lokimq/jobs.cpp:143:28: error: unused variable 'queue' [-Werror=unused-variable]
     auto& [run, busy, queue] = tagged_workers.emplace_back();
                            ^
cc1plus: all warnings being treated as errors
```

**Comment by ccdonn** [comment]
i cannot build dev branch.
here is the build fail message, any suggestion?

```
Scanning dependencies of target wallet_rpc_server
make[3]: Leaving directory '/home/ubuntu/loki/build/Linux/dev/release'
make[3]: Entering directory '/home/ubuntu/loki/build/Linux/dev/release'
[ 62%] Building CXX object src/wallet/CMakeFiles/wallet_rpc_server.dir/wallet_rpc_server.cpp.o
In file included from /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/LoopData.h:29,
                 from /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/Loop.h:23,
                 from /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/HttpContext.h:23,
                 from /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/App.h:24,
                 from /home/ubuntu/loki/src/wallet/wallet_rpc_server.h:38,
                 from /home/ubuntu/loki/src/wallet/wallet_rpc_server.cpp:43:
/home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/f2/function2.hpp: In instantiation of ‘constexpr fu2::abi_400::detail::type_erasure::erasure<IsOwning, Config, Property>::erasure(std::true_type, T&&, Allocator&&) [with T = tools::wallet_rpc_server::handle_json_rpc_request(tools::HttpResponse&, tools::HttpRequest&)::<lambda()>; Allocator = std::allocator<tools::wallet_rpc_server::handle_json_rpc_request(tools::HttpResponse&, tools::HttpRequest&)::<lambda()> >; bool IsOwning = true; Config = fu2::abi_400::detail::config<true, false, fu2::capacity_default>; Property = fu2::abi_400::detail::property<true, false, void()>; std::true_type = std::integral_constant<bool, true>]’:
/home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/f2/function2.hpp:1515:72:   required from ‘constexpr fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::function(T&&) [with T = tools::wallet_rpc_server::handle_json_rpc_request(tools::HttpResponse&, tools::HttpRequest&)::<lambda()>; fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::enable_if_not_convertible_to_this<T>* <anonymous> = 0; fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::enable_if_can_accept_all_t<T>* <anonymous> = 0; fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::assert_wrong_copy_assign_t<T>* <anonymous> = 0; fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::assert_no_strong_except_guarantee_t<T>* <anonymous> = 0; Config = fu2::abi_400::detail::config<true, false, fu2::capacity_default>; bool IsThrowing = true; bool HasStrongExceptGuarantee = false; Args = {void()}]’
/home/ubuntu/loki/src/wallet/wallet_rpc_server.cpp:202:24:   required from here
/home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/f2/function2.hpp:1131:9: error: the address of ‘static constexpr void tools::wallet_rpc_server::handle_json_rpc_request(tools::HttpResponse&, tools::HttpRequest&)::<lambda()>::_FUN()’ will never be NULL [-Werror=address]
     if (bool(callable)) {
         ^~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
```

**Comment by ccdonn** [comment]
> i cannot build dev branch.
> here is the build fail message, any suggestion?
> 
> ```
> Scanning dependencies of target wallet_rpc_server
> make[3]: Leaving directory '/home/ubuntu/loki/build/Linux/dev/release'
> make[3]: Entering directory '/home/ubuntu/loki/build/Linux/dev/release'
> [ 62%] Building CXX object src/wallet/CMakeFiles/wallet_rpc_server.dir/wallet_rpc_server.cpp.o
> In file included from /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/LoopData.h:29,
>                  from /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/Loop.h:23,
>                  from /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/HttpContext.h:23,
>                  from /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/App.h:24,
>                  from /home/ubuntu/loki/src/wallet/wallet_rpc_server.h:38,
>                  from /home/ubuntu/loki/src/wallet/wallet_rpc_server.cpp:43:
> /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/f2/function2.hpp: In instantiation of ‘constexpr fu2::abi_400::detail::type_erasure::erasure<IsOwning, Config, Property>::erasure(std::true_type, T&&, Allocator&&) [with T = tools::wallet_rpc_server::handle_json_rpc_request(tools::HttpResponse&, tools::HttpRequest&)::<lambda()>; Allocator = std::allocator<tools::wallet_rpc_server::handle_json_rpc_request(tools::HttpResponse&, tools::HttpRequest&)::<lambda()> >; bool IsOwning = true; Config = fu2::abi_400::detail::config<true, false, fu2::capacity_default>; Property = fu2::abi_400::detail::property<true, false, void()>; std::true_type = std::integral_constant<bool, true>]’:
> /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/f2/function2.hpp:1515:72:   required from ‘constexpr fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::function(T&&) [with T = tools::wallet_rpc_server::handle_json_rpc_request(tools::HttpResponse&, tools::HttpRequest&)::<lambda()>; fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::enable_if_not_convertible_to_this<T>* <anonymous> = 0; fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::enable_if_can_accept_all_t<T>* <anonymous> = 0; fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::assert_wrong_copy_assign_t<T>* <anonymous> = 0; fu2::abi_400::detail::function<Config, fu2::abi_400::detail::property<IsThrowing, HasStrongExceptGuarantee, Args ...> >::assert_no_strong_except_guarantee_t<T>* <anonymous> = 0; Config = fu2::abi_400::detail::config<true, false, fu2::capacity_default>; bool IsThrowing = true; bool HasStrongExceptGuarantee = false; Args = {void()}]’
> /home/ubuntu/loki/src/wallet/wallet_rpc_server.cpp:202:24:   required from here
> /home/ubuntu/loki/build/Linux/dev/release/external/uWebSockets/uWebSockets/f2/function2.hpp:1131:9: error: the address of ‘static constexpr void tools::wallet_rpc_server::handle_json_rpc_request(tools::HttpResponse&, tools::HttpRequest&)::<lambda()>::_FUN()’ will never be NULL [-Werror=address]
>      if (bool(callable)) {
>          ^~~~~~~~~~~~~~
> cc1plus: all warnings being treated as errors
> ```

this is all steps from a clean ubuntu18.04
```
sudo apt-get install software-properties-common python-software-properties -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test

sudo apt update

sudo apt install -y git vim curl wget unzip bzip2 gcc g++ gcc-8 g++-8 cmake pkg-config libboost-filesystem-dev libboost-thread-dev libboost-date-time-dev \
    libboost-serialization-dev libboost-program-options-dev \
    libssl-dev libzmq3-dev libsqlite3-dev libunbound-dev libsodium-dev libunwind8-dev liblzma-dev libreadline-dev \
    libldns-dev libexpat1-dev doxygen graphviz libsqlite3-dev libcurl4-openssl-dev

cd
git clone https://github.com/NLnetLabs/unbound.git
cd unbound
./configure && make -j4 && sudo make install

cd
wget https://dl.bintray.com/boostorg/release/1.73.0/source/boost_1_73_0.tar.bz2
tar --bzip2 -vxf boost_1_73_0.tar.bz2
cd boost_1_73_0
./bootstrap.sh
sudo ./b2 install

git clone https://github.com/loki-project/loki
cd loki
git checkout dev
git submodule update --init --recursive
export CC=gcc-8 CXX=g++-8
make
```

**Comment by jagerman** [comment]
That error is actually just a warning, but looks like warnings are being forced to errors (which the top-level Makefile forces on but really shouldn't).  Try to build with cmake directly: instead of that last `make` step use:
```
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ..
make -j4  # increase 4 if you have lots of cores and RAM, lower it if you don't
```
which will give you loki binaries in `loki/build/bin/`

**Comment by ccdonn** [comment]
> That error is actually just a warning, but looks like warnings are being forced to errors (which the top-level Makefile forces on but really shouldn't). Try to build with cmake directly: instead of that last `make` step use:
> 
> ```
> mkdir build
> cd build
> cmake -DCMAKE_C_COMPILER=gcc-8 -DCMAKE_CXX_COMPILER=g++-8 ..
> make -j4  # increase 4 if you have lots of cores and RAM, lower it if you don't
> ```
> 
> which will give you loki binaries in `loki/build/bin/`

cooool, now i got the binary file from dev branch, thanks!

**Comment by jagerman** [comment]
(warnings-as-errors is now disabled in the top-level Makefile on the `dev` branch with #1257 )

**Comment by ccdonn** [comment]
have do some transfer by dev branch, looks ok.

but question is, is it possible i meet the same problem on mainnet?
