### ISSUE TITLE
Fail import_key_images

### ISSUE THREAD

**Issue by ccdonn** [loki-project/loki-core#1319]
**Describe the bug**

fail to use import_key_images to import key images to watch_only_wallet on v8.1.0 and v8.1.1 release.
shows error as following.

on loki-wallet-cli
```
Error: Failed to import key images: Failed to get transaction(s) from daemon: daemon returned Failed to parse hex representation of transaction hash
```
on loki-wallet-rpc
```
2020-10-05 07:29:00.565	E res.status != rpc::STATUS_OK. THROW EXCEPTION: error::wallet_internal_error
```

**To Reproduce**
following steps were on `loki-wallet-cli`

step 1. (full) refresh
step 1a. (full) rescan_bc or rescan_spent or both
step 2. (full) export_key_images $filename
step 3. (watch_only) refresh
step 4. (watch_only) import_key_images $filename

**Expected behaviour**
What is the expected behaviour if the steps above are followed:
Import key images success like previous release(v7.1.9).

**Current Behaviour**
What is the current behaviour if the steps to reproduce are followed:
Import key images fail.

**Screenshots or Logs**
If applicable, add screenshots or logs to help explain your problem.

`Full Wallet`
```
[wallet L8of6Q (out of sync)]: refresh
Starting refresh...
Refresh done, blocks received: 2
Currently selected account: [0] Primary account
Tag: (No tag assigned)
Balance: 9.271184240, unlocked balance: 9.271184240
[wallet L8of6Q]: rescan_bc
Starting refresh...
Enter password (output received) - use the refresh command
...
[wallet L8of6Q]: rescan_spent
[wallet L8of6Q]: export_key_images kimage.t
File kimage.t already exists. Are you sure to overwrite it? (Y/Yes/N/No): Y
Wallet password:
Signed key images exported to kimage.t
```

`WatchOnly Wallet`
```
[wallet L8of6Q]:
[wallet L8of6Q (out of sync)]: refresh
Starting refresh...
Refresh done, blocks received: 2
Currently selected account: [0] Primary account
Tag: (No tag assigned)
Balance: 9.271184240, unlocked balance: 9.271184240
[wallet L8of6Q]: import_key_images kimage.t
Error: Failed to import key images: Failed to get transaction(s) from daemon: daemon returned Failed to parse hex representation of transaction hash
```

**Additional Information (please complete the following information):**
 - Operating System: [e.g. Ubuntu 16.04, Windows 10]: Centos7 / Ubuntu18.04
-  Local or Remote node mainnet
 - Version of Loki daemon, or most recent commit hash. loki-linux-x86_64-8.1.0 and loki-linux-x86_64-8.1.1

**Comment by jagerman** [comment]
This should be fixed in 8.1.2 by #1320

**Comment by ccdonn** [comment]
have tried 8.1.2 on mainnet, same problem.

`full wallet`
```
[wallet L8of6Q]: refresh
Starting refresh...
Refresh done, blocks received: 0
Currently selected account: [0] Primary account
Tag: (No tag assigned)
Balance: 9.271184240, unlocked balance: 9.271184240
[wallet L8of6Q]: rescan_bc
Starting refresh...
Enter password (output received) - use the refresh command:
...
Balance: 9.271184240, unlocked balance: 9.271184240
[wallet L8of6Q]: export_key_images kimage.t
File kimage.t already exists. Are you sure to overwrite it? (Y/Yes/N/No): Y
Wallet password:
Signed key images exported to kimage.t
```

`WatchOnly wallet`
```
[wallet L8of6Q]:
[wallet L8of6Q (out of sync)]: refresh
Starting refresh...
Refresh done, blocks received: 1
Currently selected account: [0] Primary account
Tag: (No tag assigned)
Balance: 9.271184240, unlocked balance: 9.271184240
[wallet L8of6Q]: import_key_images kimage.t
Error: Failed to import key images: Failed to get transaction(s) from daemon: daemon returned Failed to parse hex representation of transaction hash
```

**Comment by jagerman** [comment]
I was able to reproduce this, and #1331 fixes it for me.  These builds have the fix applied if you want to give it a try to confirm:

https://builds.lokinet.dev/jagerman/loki/ki-import-fix

**Comment by ccdonn** [comment]
this build works 👍

**Comment by jagerman** [comment]
Yes, but likely not for several days as we *just* put out 8.1.2 a couple days ago and I'd like to collect some more fixes before putting out a new release.  In the meantime the builds posted above, or (shortly) building from source on the `stable` branch will have the fix.

**Comment by jagerman** [comment]
(Also just cherry-picked the fix onto the `stable` branch for the next stable point release).
