### ISSUE TITLE
Failed to get transaction(s) from daemon: daemon returned Failed to parse hex representation of transaction hash

### ISSUE THREAD

**Issue by Vijay-Duke** [loki-project/loki-core#1339]
**Describe the bug**
The daemon returns error when checking transaction 

**To Reproduce**
Step 1: get the transaction hash for any sent Transaction
Step 2: run: `get_tx_key` `'Transaction_hash'`
Step 3: run: `check_tx_key` `hash` `key` `address`

**Current Behaviour**
throws an error: Failed to get transaction(s) from daemon: daemon returned Failed to parse hex representation of transaction hash

**Screenshots or Logs**
Same thing with GUI wallet

**Additional Information (please complete the following information):**
 - Operating System: [MAC]
   Local and Remote node
 - Version of Loki daemon  `v8.1.2-release`

**Comment by jagerman** [comment]
I looked into this; it is fixed on current `dev` (was fixed by #1331), and will be in the next wallet update which should be out this week.

**Comment by jagerman** [comment]
Fixed in 8.1.3.
