### ISSUE TITLE
loki-wallet-rpc with --help leaves the terminal text bold

### ISSUE THREAD

**Issue by Doy-lee** [loki-project/loki-core#428]
Steps To Reproduce
1. ./loki-wallet-rpc --help

Observe the terminal text is now bold.
![bolded_text](https://user-images.githubusercontent.com/12163539/53064131-cca07380-351a-11e9-89e9-351a55462cca.png)

**Comment by Hangus-Udson** [comment]
I'll have a look at it!

**Comment by javabudd** [comment]
close this one?
